[package]
name = "pyglue"
version = "0.1.1"
edition = "2024"
license = "MIT"
description = "Python Rust interface"
repository = "https://github.com/Garrett323/pyglue"
readme = "README.md"
keywords = ["python", "pyo3"]
categories = ["development-tools"]

[dependencies]
ndarray = "0.17.2"
numpy = "0.29.0"
pyo3 = { version = "0.29.1", features = ["extension-module"] }
rayon = "1.12.0"
serde = {version = "1.0.229", features = ["derive"]}

