[build-system]
requires = ["maturin>=1.12,<2.0"]
build-backend = "maturin"

[project]
name = "pyglue-rs"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tk", email = "tkochs@proton.me" }
]
requires-python = ">=3.11"
dependencies = [
    "maturin>=1.14.1",
]
dynamic = ["version"]


[dependency-groups]
dev = [
    "pandas>=3.0.5",
    "pytest>=9.1.1",
]
